services:
  api:
    build: .
    container_name: api
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env # Carrega as vari치veis de ambiente do arquivo .env
    depends_on:
      db:
        condition: service_healthy # Garante que a API s칩 inicie quando o DB estiver saud치vel

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env # Usa as mesmas vari치veis para configurar o banco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
