"""Add hashed_password to Aluno model

Revision ID: 61e15fd129db
Revises: 24919f622bbe
Create Date: 2025-07-09 11:55:04.189358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e15fd129db'
down_revision: Union[str, Sequence[str], None] = '24919f622bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_index(op.f('ix_alunos_email'), 'alunos', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alunos_email'), table_name='alunos')
    op.drop_column('alunos', 'hashed_password')
    # ### end Alembic commands ###
